project_id = "srwnjnrhxzcpftmbbyib"

[functions.send_invite]
# Requires authentication - admin only

[functions.orquest_proxy]
verify_jwt = false

[functions.sync_orquest_services]
verify_jwt = false

[functions.sincronizar-orquest-servicios]
verify_jwt = false

[functions.check_system_health]
verify_jwt = false

[functions.import_restaurants_csv]
verify_jwt = false
